const stays = [
  {name:"AZZA Smart Stay",type:"Hotel · studio",area:"Trindade / Carvoeira",distance:"~700 m da UFSC",band:"economico",price:212,high:300,tag:"MELHOR PREÇO",rating:"9,5",image:"https://content.r9cdn.net/rimg/himg/e4/cc/99/expedia_group-1071214195-78931192-905480.jpg?crop=true&height=630&width=1200",alt:"Quarto do AZZA Smart Stay com janela ampla e luz natural",link:"https://azzahoteis.com.br/",source:"Decolar · R$212 observado em 27/09/26",description:"Studio prático com estrutura de hotel, estacionamento e acesso fácil à UFSC."},
  {name:"Quinta da Bica d’Água",type:"Hotel · jardim",area:"Carvoeira / Saco dos Limões",distance:"~1 km da UFSC",band:"economico",price:207,high:330,tag:"CHARME + CUSTO",rating:"7,0",image:"https://cf.bstatic.com/xdata/images/hotel/max1024x768/630228301.jpg?k=c327b0cded9e2586a2e978b96a63107c4e24a4f046cc0d53ef41af30ca451877&o=",alt:"Jardim e fachada da Quinta da Bica d’Água",link:"http://hotelquintadabicadagua.com.br/site/",source:"KAYAK · tarifas recentes a partir de R$207",description:"Um hotel com clima de pousada, jardim e estacionamento. Boa posição para UFSC e centro."},
  {name:"Studio perto da UFSC",type:"Apartamento · Airbnb",area:"Trindade",distance:"~650 m da UFSC",band:"airbnb",price:220,high:380,tag:"BEM LOCALIZADO",rating:"—",image:"https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=80",alt:"Interior de apartamento compacto e iluminado",link:"https://www.airbnb.com/rooms/1315101960242814941",source:"Airbnb · anúncio; preço depende das datas",description:"Estúdio anunciado como perto da UFSC. A opção de apê pode ajudar quem quer cozinha e autonomia."},
  {name:"Apê no Pantanal perto da UFSC",type:"Apartamento · Airbnb",area:"Pantanal",distance:"~1 km da UFSC",band:"airbnb",price:240,high:420,tag:"PERTO DA FESTA",rating:"—",image:"https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",alt:"Sala de apartamento com decoração aconchegante",link:"https://www.airbnb.com/ufsc-florianopolis-brazil/stays/apartments",source:"Airbnb · busca na região da UFSC",description:"Alternativa em bairro residencial, com acesso rápido ao campus e ao eixo Pantanal/Trindade."},
  {name:"Studio acima do Angeloni",type:"Apartamento · Airbnb",area:"Trindade",distance:"~800 m da UFSC",band:"airbnb",price:250,high:430,tag:"PRÁTICO",rating:"—",image:"https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=900&q=80",alt:"Sala de estar moderna em tons claros",link:"https://www.airbnb.com/ufsc-florianopolis-brazil/stays/apartments",source:"Airbnb · opção aparece na busca regional; confirme a unidade",description:"Há anúncios bem avaliados perto da UFSC; confirme qual unidade e endereço ao abrir a busca."},
  {name:"Interclass Florianópolis",type:"Hotel · café da manhã",area:"Trindade",distance:"~500 m da UFSC",band:"medio",price:356,high:440,tag:"MAIS PERTO",rating:"8,5",image:"https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=900&q=80",alt:"Hotel com piscina e fachada contemporânea",link:"https://book.omnibees.com/chain/7864/hotel/13424?errredir=1",source:"Decolar e canal oficial · R$356–412 em consultas recentes",description:"Hotel tradicional ao lado da universidade, com recepção e serviços. Excelente para quem quer resolver tudo a pé."},
  {name:"Mercure Florianópolis",type:"Hotel · rede",area:"Itacorubi",distance:"~2 km da UFSC",band:"medio",price:389,high:640,tag:"CONFORTO NO ITACORUBI",rating:"—",image:"https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=900&q=80",alt:"Fachada de hotel urbano",link:"https://all.accor.com/hotel/5693/index.pt-br.shtml",source:"Acordo tarifário 2026 consultado · standard duplo R$389",description:"Hotel de rede na Rodovia Admar Gonzaga. Referência pública de tarifa corporativa; confirme elegibilidade e tarifa direta."},
  {name:"Hotel São José",type:"Hotel · econômico",area:"São José",distance:"~12 km da UFSC",band:"medio",price:250,high:380,tag:"NO CONTINENTE",rating:"—",image:"https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=900&q=80",alt:"Quarto de hotel confortável",link:"https://www.saojosehotel.com.br/",source:"Site oficial · tarifa consultar",description:"Hotel novo, com acesso prático à BR-101. Pode compensar para convidados de carro; confira o trajeto nos horários de pico."},
  {name:"Kennedy Executive Hotel",type:"Hotel · café da manhã",area:"Campinas, São José",distance:"~11 km da UFSC",band:"medio",price:322,high:460,tag:"SÃO JOSÉ",rating:"—",image:"https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&w=900&q=80",alt:"Quarto de hotel com cama de casal",link:"https://hotelkennedy.com.br/",source:"KAYAK · a partir de R$322; média recente R$387",description:"Boa estrutura no bairro Campinas e acesso conveniente a serviços. Distante da UFSC, mas útil para quem ficará no continente."},
  {name:"K-Platz Hotel",type:"Hotel · superior",area:"Campinas, São José",distance:"~10 km da UFSC",band:"conforto",price:415,high:560,tag:"MAIS CONFORTO",rating:"9,8",image:"https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=900&q=80",alt:"Quarto amplo de hotel com janela panorâmica",link:"https://book.omnibees.com/chain/7242/hotel/13440?currencyId=109&lang=pt-BR&q=13440",source:"Expedia · R$415 observado; canal oficial desde R$528",description:"Quartos amplos dentro do K-Platz Center, com restaurantes e serviços por perto. Boa escolha para quem valoriza conforto."},
  {name:"Don Zepe Hotel",type:"Hotel · centrinho da Lagoa",area:"Lagoa da Conceição",distance:"~6 km · ~15 min de carro",band:"medio",price:282,high:393,tag:"LAGOA DA CONCEIÇÃO",rating:"—",image:"https://images.trvl-media.com/lodging/5000000/4350000/4344200/4344191/81ab536d.jpg?impolicy=resizecrop&ra=fill&rh=575&rw=575",alt:"Entrada do Don Zepe Hotel à noite",link:"https://www.donzepehotel.com.br/",source:"KAYAK/Expedia · referências recentes de R$282–393/noite. Distância/tempo conforme lista enviada.",description:"No centrinho da Lagoa, perto de restaurantes e da beira da água. Boa opção para quem quer aproveitar o bairro também."},
  {name:"Pousada Native",type:"Pousada · piscina e jardim",area:"Lagoa da Conceição",distance:"~6 km · ~15 min de carro",band:"conforto",price:402,high:642,tag:"ACONCHEGO",rating:"9,2",image:"https://cf.bstatic.com/xdata/images/hotel/max1024x768/319522647.jpg?k=64c7972efd1d76f147074b1493367421e90d32f059f19273cf27cfdff075323a&o=",alt:"Quarto claro da Pousada Native com cama de casal e solteiro",link:"https://www.booking.com/hotel/br/native-poshtel.pt-br.html",source:"Booking/Decolar · referências recentes de R$402–642/noite. Distância/tempo conforme lista enviada.",description:"Pousada bem avaliada na Lagoa, com quartos familiares, jardim e piscina. Confirme o tipo de quarto e acesso por escadas."},
];

const brl = n => n.toLocaleString('pt-BR', {style:'currency',currency:'BRL',maximumFractionDigits:0});
const card = s => `<article class="stay-card" data-band="${s.band}" data-price="${s.price}" data-distance="${Number(s.distance.match(/[\d,.]+/)[0].replace(',','.'))}">
  <a class="photo-link" href="${s.link}" target="_blank" rel="noreferrer" aria-label="Consultar ${s.name}"><img class="stay-photo" src="${s.image}" alt="${s.alt}" loading="lazy"><span class="photo-tag">${s.tag}</span><span class="photo-arrow">↗</span></a>
  <div class="card-body"><div class="card-meta"><span>${s.type}</span><span class="rating">${s.rating !== '—' ? `★ ${s.rating}` : 'CONSULTAR'}</span></div><h3>${s.name}</h3><div class="location"><span>⌖</span> ${s.area} <i>·</i> ${s.distance}</div><p class="description">${s.description}</p><div class="price-row"><div><small>DIÁRIA REF. / 2 PESSOAS</small><strong>${brl(s.price)}<small class="to">– ${brl(s.high)}</small></strong><span class="total-est">11 noites: ${brl(s.price*11)}–${brl(s.high*11)}*</span></div><a class="book-link" href="${s.link}" target="_blank" rel="noreferrer">ver opções <span>↗</span></a></div><div class="source-note">${s.source}</div></div></article>`;

let activeFilter = 'all';
const cardsEl = document.querySelector('#cards');
function render(){
  const sort = document.querySelector('#sort').value;
  let list = stays.filter(s => activeFilter === 'all' || (activeFilter === 'airbnb' ? s.band === 'airbnb' : s.band === activeFilter));
  if(sort === 'price') list.sort((a,b)=>a.price-b.price);
  if(sort === 'distance') list.sort((a,b)=>Number(a.distance.match(/[\d,.]+/)[0].replace(',','.'))-Number(b.distance.match(/[\d,.]+/)[0].replace(',','.')));
  cardsEl.innerHTML = list.map(card).join('');
  document.querySelector('#result-count').textContent = `${list.length} ${list.length === 1 ? 'lugar' : 'lugares'}`;
  document.querySelector('#empty-state').hidden = list.length > 0;
}
document.querySelectorAll('.filter').forEach(btn => btn.addEventListener('click',()=>{document.querySelector('.filter.active').classList.remove('active');btn.classList.add('active');activeFilter=btn.dataset.filter;render()}));
document.querySelector('#sort').addEventListener('change',render);
document.querySelector('#font-toggle').addEventListener('click', event => {
  const enabled = document.body.classList.toggle('text-xl');
  event.currentTarget.setAttribute('aria-pressed', String(enabled));
  event.currentTarget.setAttribute('aria-label', enabled ? 'Diminuir tamanho do texto' : 'Aumentar tamanho do texto');
  event.currentTarget.innerHTML = enabled ? 'A− <span>texto menor</span>' : 'A+ <span>texto maior</span>';
});
render();
